name: 'Automatic Semver Release'
description: 'Github Semver Automatic Release'
branding:
  icon: 'box'
  color: 'yellow'
inputs:
  TOKEN:
    description: 'Secret token from GitHub'
    required: true
    default: ''
  SEMVER:
    description:
      'Which version you want to increment? Use MAJOR, MINOR or PATCH'
    required: false
    default: 'PATCH'
  LABEL:
    description: 'Add Labels. i.e final, alpha, rc'
    required: false
    default: ''
  MAIN_BRANCH:
    description: 'The name of your main branch'
    required: false
    default: 'main'
  NOTES:
    description: 'Text to include as the changelog'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SEMVER }}
    - ${{ inputs.MAIN_BRANCH }}
    - ${{ inputs.TOKEN }}
    - ${{ inputs.NOTES }}
    - ${{ inputs.LABEL }}
