name: 'Verify'

on:
  push:
jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'

    steps:
      # Checkout production branch
      - name: 'Checkout'
        uses: actions/checkout@v2

      # Execute tests
      - name: 'Execute tests'
        run: ./entrypoint.test.sh
